spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/order_ingestor_db
    username: ${DB_USER:postgres}
    password: ${DB_PASS:postgres}

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: order-ingestor-local

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  metrics:
    export:
      prometheus:
        enabled: true